### PR TITLE
Update NETWORKING.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mhammadsaani** [comment]
Hey @Shyamu431, as this repo is on initial stages. There is possibility of more errors in the future. So, if you are interested I can assign this issue to you!

**Comment by ghost** [comment]
Yes, there are many more errors which need to be fixed.

**Comment by mhammadsaani** [comment]
I am assigning this issue to you and try to make at least 10/15 corrections before making a PR.

**Comment by ghost** [comment]
> I am assigning this issue to you and try to make at least 10/15 corrections before making a PR.

Thank you for providing me this opportunity.I'll do my best.

**Pull request merged**
